name: Terraform Master Workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  some:
    runs-on: ubuntu-latest
    steps:
    - name: print ls
      run: ls
    - name: print pwd
      run: pwd
    - name: print la
      run: ls -la

  preCommitCheck:
    name: Terraform Checks
    uses: ./.github/workflows/terraform-checks.yaml

  generateDocs:
    name: Generate Terraform Docs
    uses: ./.github/workflows/terraform-docs.yaml
