name: Terraform Master Workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  preCommitCheck:
    name: Terraform Checks
    uses: ./.github/workflows/terraform-checks.yaml@main

  generateDocs:
    name: Generate Terraform Docs
    uses: ./.github/workflows/terraform-docs.yaml@main
