name: Terraform Master Workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  preCommitCheck:
    name: Terraform Checks
    uses: ./.github/workflows/terraform-checks.yaml

  generateDocs:
    name: Generate Terraform Docs
    needs: preCommitCheck
    uses: ./.github/workflows/terraform-docs.yaml

  release:
    name: Release module
    needs: generateDocs
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/release.yaml
